const options: string[] = [
"Hello",
"How are you",
"What is your name",
"Nice to meet you",
"Where are you from",
"What do you do",
"How is the weather",
"What time is it",
"Can you help me please",
"Sorry",
"Thank you",
"Excuse me",
"I am sorry I do not understand",
"Could you repeat that please",
"Where is the restroom",
"How much does it cost",
"I would like to order",
"What is the Wi-Fi password",
"Do you have a menu",
"Can I have the check please",
"Have a nice day",
"I love you",
"What is your favorite color",
"How old are you",
"Happy birthday",
"Congratulations",
"Good luck",
"I am hungry",
"I am thirsty",
"Can I have a glass of water please",
"What is your favorite food",
"I am tired",
"I am bored",
"What are you doing",
"Let us go",
"I do not know",
"I am lost",
"Can you show me on the map",
"What is your phone number",
"Do you have any recommendations",
"Where can I find a good restaurant",
"Can you speak slower please",
"Can you help me find my way",
"I need a doctor",
"Call the police",
"I am sorry for the mistake",
"What is the capital of this country",
"Can I borrow a pen",
"I am going on vacation",
"What is your favorite movie",
"Do you have any siblings",
"What is your favorite sport",
"I do not like this",
"I do not understand",
"I am not sure",
"Can you explain that again",
"What is the nearest bus stop",
"Is this seat taken",
"Are you free tonight",
"Can you recommend a good book",
"Where is the nearest ATM",
"How do I get to the train station",
"What is the best way to get there",
"I will have a coffee please",
"Can I have some sugar please",
"Do you accept credit cards",
"Is there a pharmacy nearby",
"I need to make a reservation",
"What is the weather forecast for tomorrow",
"Do you have any vegetarian options",
"I am allergic to peanuts",
"What is the time difference",
"Can I try this on",
"How do I use this",
"Can you recommend a good hotel",
"Can I have a refund",
"Where can I buy tickets",
"How do I say this in English",
"Do you have a charger I can borrow",
"I will take the red one",
"Can you help me with my luggage",
"Where can I find a taxi",
"Is there a bank nearby",
"Can you speak English",
"I am sorry to hear that",
"Do you have any pets",
"I am excited",
"I am scared",
"Can you recommend a good restaurant",
"Where can I find a restroom",
"What is your favorite book",
"Do you have any recommendations for sightseeing",
"I am looking for a job",
"I am going shopping",
"Can you give me directions",
"Can I have a receipt please",
"Is there a public transportation system",
"What is your favorite music",
"Can I take a picture",
"How are you doing",
"What is your favorite movie genre",
"Where do you work",
"What kind of music do you like",
"Do you prefer tea or coffee",
"How do I get to the airport",
"What is your favorite season",
"What is your dream job",
"How do I get to the nearest bus stop",
"Do you like sports",
"How do I use the elevator",
"Where can I get a taxi",
"Do you like to read books",
"Do you watch movies often",
"What is your favorite hobby",
"Where is the nearest coffee shop",
"Do you enjoy traveling",
"Where do you live",
"Can you tell me the way to the station",
"How long will it take to get there",
"Can I have a bottle of water",
"Do you like to cook",
"Where can I buy clothes",
"Can I take this seat",
"Is it cold outside",
"How many people are in your family",
"What kind of food do you like",
"What is the best way to stay healthy",
"Where can I find a gym",
"How do I get to the museum",
"Do you play any instruments",
"Do you like to go hiking",
"What is your favorite type of cuisine",
"How often do you exercise",
"Do you like art",
"What is your favorite holiday",
"How do I get to the shopping mall",
"Can I help you with anything",
"Where can I buy shoes",
"How do I get a ticket for the train",
"What is the best restaurant in the area",
"Can you show me your ID",
"Do you have a favorite place to visit",
"What time do you get off work",
"Can you speak any other languages",
"Where can I find some good food",
"How much do I owe you"
];

export default options;
